struct WhisperLanguage: Identifiable, Hashable {
    let id: String // ISO 639-1 code
    let name: String
    let flag: String

    var displayText: String {
        "\(self.flag) \(self.name)"
    }

    func matches(_ query: String) -> Bool {
        let lowercasedQuery = query.lowercased()
        return self.name.lowercased().contains(lowercasedQuery) ||
            self.id.lowercased().contains(lowercasedQuery)
    }

    static let autoDetect = WhisperLanguage(id: "", name: "Auto-detect", flag: "🌐")

    static let allLanguages: [WhisperLanguage] = [
        WhisperLanguage(id: "en", name: "English", flag: "🇬🇧"),
        WhisperLanguage(id: "zh", name: "Chinese", flag: "🇨🇳"),
        WhisperLanguage(id: "de", name: "German", flag: "🇩🇪"),
        WhisperLanguage(id: "es", name: "Spanish", flag: "🇪🇸"),
        WhisperLanguage(id: "ru", name: "Russian", flag: "🇷🇺"),
        WhisperLanguage(id: "ko", name: "Korean", flag: "🇰🇷"),
        WhisperLanguage(id: "fr", name: "French", flag: "🇫🇷"),
        WhisperLanguage(id: "ja", name: "Japanese", flag: "🇯🇵"),
        WhisperLanguage(id: "pt", name: "Portuguese", flag: "🇵🇹"),
        WhisperLanguage(id: "tr", name: "Turkish", flag: "🇹🇷"),
        WhisperLanguage(id: "pl", name: "Polish", flag: "🇵🇱"),
        WhisperLanguage(id: "ca", name: "Catalan", flag: "🇪🇸"),
        WhisperLanguage(id: "nl", name: "Dutch", flag: "🇳🇱"),
        WhisperLanguage(id: "ar", name: "Arabic", flag: "🇸🇦"),
        WhisperLanguage(id: "sv", name: "Swedish", flag: "🇸🇪"),
        WhisperLanguage(id: "it", name: "Italian", flag: "🇮🇹"),
        WhisperLanguage(id: "id", name: "Indonesian", flag: "🇮🇩"),
        WhisperLanguage(id: "hi", name: "Hindi", flag: "🇮🇳"),
        WhisperLanguage(id: "fi", name: "Finnish", flag: "🇫🇮"),
        WhisperLanguage(id: "vi", name: "Vietnamese", flag: "🇻🇳"),
        WhisperLanguage(id: "he", name: "Hebrew", flag: "🇮🇱"),
        WhisperLanguage(id: "uk", name: "Ukrainian", flag: "🇺🇦"),
        WhisperLanguage(id: "el", name: "Greek", flag: "🇬🇷"),
        WhisperLanguage(id: "ms", name: "Malay", flag: "🇲🇾"),
        WhisperLanguage(id: "cs", name: "Czech", flag: "🇨🇿"),
        WhisperLanguage(id: "ro", name: "Romanian", flag: "🇷🇴"),
        WhisperLanguage(id: "da", name: "Danish", flag: "🇩🇰"),
        WhisperLanguage(id: "hu", name: "Hungarian", flag: "🇭🇺"),
        WhisperLanguage(id: "ta", name: "Tamil", flag: "🇮🇳"),
        WhisperLanguage(id: "no", name: "Norwegian", flag: "🇳🇴"),
        WhisperLanguage(id: "th", name: "Thai", flag: "🇹🇭"),
        WhisperLanguage(id: "ur", name: "Urdu", flag: "🇵🇰"),
        WhisperLanguage(id: "hr", name: "Croatian", flag: "🇭🇷"),
        WhisperLanguage(id: "bg", name: "Bulgarian", flag: "🇧🇬"),
        WhisperLanguage(id: "lt", name: "Lithuanian", flag: "🇱🇹"),
        WhisperLanguage(id: "la", name: "Latin", flag: "🇻🇦"),
        WhisperLanguage(id: "mi", name: "Maori", flag: "🇳🇿"),
        WhisperLanguage(id: "ml", name: "Malayalam", flag: "🇮🇳"),
        WhisperLanguage(id: "cy", name: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
        WhisperLanguage(id: "sk", name: "Slovak", flag: "🇸🇰"),
        WhisperLanguage(id: "te", name: "Telugu", flag: "🇮🇳"),
        WhisperLanguage(id: "fa", name: "Persian", flag: "🇮🇷"),
        WhisperLanguage(id: "lv", name: "Latvian", flag: "🇱🇻"),
        WhisperLanguage(id: "bn", name: "Bengali", flag: "🇧🇩"),
        WhisperLanguage(id: "sr", name: "Serbian", flag: "🇷🇸"),
        WhisperLanguage(id: "az", name: "Azerbaijani", flag: "🇦🇿"),
        WhisperLanguage(id: "sl", name: "Slovenian", flag: "🇸🇮"),
        WhisperLanguage(id: "kn", name: "Kannada", flag: "🇮🇳"),
        WhisperLanguage(id: "et", name: "Estonian", flag: "🇪🇪"),
        WhisperLanguage(id: "mk", name: "Macedonian", flag: "🇲🇰"),
        WhisperLanguage(id: "br", name: "Breton", flag: "🇫🇷"),
        WhisperLanguage(id: "eu", name: "Basque", flag: "🇪🇸"),
        WhisperLanguage(id: "is", name: "Icelandic", flag: "🇮🇸"),
        WhisperLanguage(id: "hy", name: "Armenian", flag: "🇦🇲"),
        WhisperLanguage(id: "ne", name: "Nepali", flag: "🇳🇵"),
        WhisperLanguage(id: "mn", name: "Mongolian", flag: "🇲🇳"),
        WhisperLanguage(id: "bs", name: "Bosnian", flag: "🇧🇦"),
        WhisperLanguage(id: "kk", name: "Kazakh", flag: "🇰🇿"),
        WhisperLanguage(id: "sq", name: "Albanian", flag: "🇦🇱"),
        WhisperLanguage(id: "sw", name: "Swahili", flag: "🇹🇿"),
        WhisperLanguage(id: "gl", name: "Galician", flag: "🇪🇸"),
        WhisperLanguage(id: "mr", name: "Marathi", flag: "🇮🇳"),
        WhisperLanguage(id: "pa", name: "Punjabi", flag: "🇮🇳"),
        WhisperLanguage(id: "si", name: "Sinhala", flag: "🇱🇰"),
        WhisperLanguage(id: "km", name: "Khmer", flag: "🇰🇭"),
        WhisperLanguage(id: "sn", name: "Shona", flag: "🇿🇼"),
        WhisperLanguage(id: "yo", name: "Yoruba", flag: "🇳🇬"),
        WhisperLanguage(id: "so", name: "Somali", flag: "🇸🇴"),
        WhisperLanguage(id: "af", name: "Afrikaans", flag: "🇿🇦"),
        WhisperLanguage(id: "oc", name: "Occitan", flag: "🇫🇷"),
        WhisperLanguage(id: "ka", name: "Georgian", flag: "🇬🇪"),
        WhisperLanguage(id: "be", name: "Belarusian", flag: "🇧🇾"),
        WhisperLanguage(id: "tg", name: "Tajik", flag: "🇹🇯"),
        WhisperLanguage(id: "sd", name: "Sindhi", flag: "🇵🇰"),
        WhisperLanguage(id: "gu", name: "Gujarati", flag: "🇮🇳"),
        WhisperLanguage(id: "am", name: "Amharic", flag: "🇪🇹"),
        WhisperLanguage(id: "yi", name: "Yiddish", flag: "🇮🇱"),
        WhisperLanguage(id: "lo", name: "Lao", flag: "🇱🇦"),
        WhisperLanguage(id: "uz", name: "Uzbek", flag: "🇺🇿"),
        WhisperLanguage(id: "fo", name: "Faroese", flag: "🇫🇴"),
        WhisperLanguage(id: "ht", name: "Haitian Creole", flag: "🇭🇹"),
        WhisperLanguage(id: "ps", name: "Pashto", flag: "🇦🇫"),
        WhisperLanguage(id: "tk", name: "Turkmen", flag: "🇹🇲"),
        WhisperLanguage(id: "nn", name: "Nynorsk", flag: "🇳🇴"),
        WhisperLanguage(id: "mt", name: "Maltese", flag: "🇲🇹"),
        WhisperLanguage(id: "sa", name: "Sanskrit", flag: "🇮🇳"),
        WhisperLanguage(id: "lb", name: "Luxembourgish", flag: "🇱🇺"),
        WhisperLanguage(id: "my", name: "Myanmar", flag: "🇲🇲"),
        WhisperLanguage(id: "bo", name: "Tibetan", flag: "🇨🇳"),
        WhisperLanguage(id: "tl", name: "Tagalog", flag: "🇵🇭"),
        WhisperLanguage(id: "mg", name: "Malagasy", flag: "🇲🇬"),
        WhisperLanguage(id: "as", name: "Assamese", flag: "🇮🇳"),
        WhisperLanguage(id: "tt", name: "Tatar", flag: "🇷🇺"),
        WhisperLanguage(id: "haw", name: "Hawaiian", flag: "🇺🇸"),
        WhisperLanguage(id: "ln", name: "Lingala", flag: "🇨🇩"),
        WhisperLanguage(id: "ha", name: "Hausa", flag: "🇳🇬"),
        WhisperLanguage(id: "ba", name: "Bashkir", flag: "🇷🇺"),
        WhisperLanguage(id: "jw", name: "Javanese", flag: "🇮🇩"),
        WhisperLanguage(id: "su", name: "Sundanese", flag: "🇮🇩"),
        WhisperLanguage(id: "yue", name: "Cantonese", flag: "🇭🇰"),
    ]
}
